### ISSUE TITLE
NLog third-party logging library crashing because of NATS library logger arguments

### ISSUE THREAD

**Issue by robertmircea** [nats-io/nats.net.v2#243]
### Observed behavior

Nats debug log in `NatsJSConsume.ctor` crashes `NLog` when trying to parse `{@Config}`. It is possible that `{@...}` is used also in other places in the library. I haven't checked.

`NATS.Client.JetStream.Internal.NatsJSConsume.ctor`
```cs
      if (this._debug)
        this._logger.LogDebug(NatsJSLogEvents.Config, "Consume setup {@Config}", (object) new
        {
          maxMsgs = maxMsgs,
          thresholdMsgs = thresholdMsgs,
          maxBytes = maxBytes,
          thresholdBytes = thresholdBytes,
          expires = expires,
          idle = idle,
          _hbTimeout = this._hbTimeout
        });
```

```
System.AggregateException: An error occurred while writing to logger(s). (Input string was not in a correct format. Failure to parse near offset 15. Expected an ASCII digit.)
 ---> System.FormatException: Input string was not in a correct format. Failure to parse near offset 15. Expected an ASCII digit.
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at NLog.Internal.LogMessageStringFormatter.FormatMessage(LogEventInfo logEvent)
   at NLog.LogEventInfo.CalcFormattedMessage()
   at NLog.LogEventInfo.SetMessageFormatter(LogMessageFormatter messageFormatter, LogMessageFormatter singleTargetMessageFormatter)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targetsForLevel, LogEventInfo logEvent, LogFactory logFactory)
   at NLog.Logger.WriteToTargets(Type wrapperType, LogEventInfo logEvent, TargetWithFilterChain targetsForLevel)
   at NLog.Logger.Log(Type wrapperType, LogEventInfo logEvent)
   at NLog.Extensions.Logging.NLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|14_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at NATS.Client.JetStream.Internal.NatsJSConsume`1..ctor(Int64 maxMsgs, Int64 thresholdMsgs, Int64 maxBytes, Int64 thresholdBytes, TimeSpan expires, TimeSpan idle, NatsJSContext context, String stream, String consumer, String subject, String queueGroup, Func`3 notificationHandler, INatsDeserialize`1 serializer, NatsSubOpts opts, CancellationToken cancellationToken)
   at NATS.Client.JetStream.NatsJSConsumer.ConsumeInternalAsync[T](INatsDeserialize`1 serializer, NatsJSConsumeOpts opts, CancellationToken cancellationToken)
   at NATS.Client.JetStream.NatsJSConsumer.ConsumeAsync[T](INatsDeserialize`1 serializer, NatsJSConsumeOpts opts, CancellationToken cancellationToken)+MoveNext()
   at NATS.Client.JetStream.NatsJSConsumer.ConsumeAsync[T](INatsDeserialize`1 serializer, NatsJSConsumeOpts opts, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Nats.NatsV2ConsumerProcessor`1.CreateProcessor(NatsConsumerMessageProcessorOptions`1 options)
```

### Expected behavior

Not to crash

### Server and client version

nuget client: 2.0.0

### Host environment

MacOS Sonoma

### Steps to reproduce

1. register NLog as logger factory
```cs
    builder.Host.UseNLog(new NLogProviderOptions
    {
        IncludeScopes = true,
        CaptureMessageProperties = true,
        ShutdownOnDispose = true
    });
```
2. Initialize `NatsConnectionPool` with
```cs
 builder.Services.AddNats();
```
3. try to create a consumer

**Comment by snakefoot** [comment]
What version of `NLog.Extensions.Logging`-nuget-package are being used? Does it also fail with latest version of `NLog.Extensions.Logging` ?

The idea is that `NLog.Extensions.Logging` should recognize the use of `{@Config}`, and avoid using `string.Format` or `Microsoft.Extension.Logging` but use NLog's own message-template-formatter.

**Comment by robertmircea** [comment]
NLog - 5.2.6
NLog.Extensions.Hosting - 5.3.5
NLog.Extensions.Logging - 5.3.5

**Comment by snakefoot** [comment]
Have tried to reproduce the issue, but failed. Are you able to make a small example project where this fails:
```c#
    builder.Host.UseNLog(new NLogProviderOptions
    {
        IncludeScopes = true,
        CaptureMessageProperties = true,
        ShutdownOnDispose = true
    });
    var host = builder.Buid();
    var programLogger = host.Services.GetService<Microsoft.Extensions.Logging.ILogger<Program>>();
    programLogger.LogDebug(42, "Consume setup {@Config}", (object) new { Name = "Bob", Age = 42 });
```
And attach to this issue, without dependencies on anything except:
- NLog - 5.2.6
- NLog.Extensions.Hosting - 5.3.5
- NLog.Extensions.Logging - 5.3.5

**Comment by mtmk** [comment]
would it be easier for us to just list all variables rather than using an object? I can make sure we don't use the `@` placeholder if this may cause issues with different loggers.

**Comment by robertmircea** [comment]
I think this will ensure compatibility for all, indeed.

**Comment by snakefoot** [comment]
Notice passing anonymous object (Ex. `new { Name = "Bob", Age = 42 }`) using `"Consume setup {Config}"` will also print all properties, since default ToString-implementation does the job.

But still interested how @robertmircea has configured NLog, because it should not fail.
