### ISSUE TITLE
Add validation for stream name when contains illegal characters

### ISSUE THREAD

**Issue by StKolev** [nats-io/nats.net.v2#357]
### Proposed change

Based on jetStream [Docs](https://docs.nats.io/nats-concepts/jetstream/streams#configuration), `Name` cannot contain whitespace, `.`, `*`, `>`, path separators (forward or backwards slash), and non-printable characters. I think it will be easy to add such validation with more descriptive message.
Thanks

### Use case

When I'm creating a stream with name containing invalid characters like`.` I'm receiving the following stack trace which does not give much information about the problem.
`NATS.Client.JetStream.NatsJSApiNoResponseException: No API response received from the server
   at NATS.Client.JetStream.NatsJSContext.JSRequestAsync[TRequest,TResponse](String subject, TRequest request, CancellationToken cancellationToken)
   at NATS.Client.JetStream.NatsJSContext.JSRequestAsync[TRequest,TResponse](String subject, TRequest request, CancellationToken cancellationToken)
   at NATS.Client.JetStream.NatsJSContext.JSRequestResponseAsync[TRequest,TResponse](String subject, TRequest request, CancellationToken cancellationToken)
   at NATS.Client.JetStream.NatsJSContext.CreateStreamAsync(StreamConfig config, CancellationToken cancellationToken)`

### Contribution

yes I can try :)

**Comment by mtmk** [comment]
JetStream models were generated from schemas and we used to have a validation routine running against the model annotations. Unfortunately we had to remove that and rely on server validating the model because model validation did not work with AOT deployments.

https://github.com/nats-io/nats.net.v2/blob/v2.0.3/src/NATS.Client.JetStream/NatsJSContext.cs#L199

Not sure if that's the way to go but we can certainly do with validating request and we should look into this. Your assistance would be greatly appreciated 💯
